# Generated by Django 5.1.1 on 2024-12-17 07:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('expire_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2026), django.core.validators.MaxValueValidator(2026)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.company')),
            ],
        ),
    ]
